ALTER TABLE repos ADD COLUMN auth_type TEXT DEFAULT NULL;
ALTER TABLE repos ADD COLUMN auth_ssh_key_path TEXT DEFAULT NULL;
ALTER TABLE repos ADD COLUMN auth_username TEXT DEFAULT NULL;
ALTER TABLE repos ADD COLUMN auth_password_env TEXT DEFAULT NULL;
